name: Automated Testing with PHPUnit

on: [ 'push' ]

jobs:
    test-bundle:
        runs-on: ubuntu-latest
        
        steps:
            -   uses: actions/checkout@v4
                
            -   uses: setup-php/setup-php@v2
                with:
                    php-version: 8.2
                    tools: composer
                    coverage: xdebug
                    
            -   run: |
                    composer install --no-interaction --no-progress
                    vendor/bin/phpunit
