name: Automated Testing with PHPUnit

on: [ 'push' ]

jobs:
    test-bundle:
        runs-on: ubuntu-latest
        
        steps:
            -   uses: actions/checkout@v4
            -   uses: php-actions/composer@v6
            -   uses: php-actions/phpunit@v3   