name: Automated Testing with PHPUnit

on: [ 'push' ]

jobs:
    test-bundle:
        runs-on: ubuntu-latest
        steps:
            -   uses: ebitkov/build-symfony-bundle@main
                with:
                    run-tests: false
                    composer-additional-dependencies: twig test
            -   run: php bundle/.github/configure.php
            -   run: symfony php bin/phpunit bundle/tests/