name: Static Analysis with PHPStan

on:
    push:
        paths:
            - .github/workflow/static-analysis.yaml
            - composer.*
            - src/**
            - test/**

jobs:
    phpstan:
        runs-on: ubuntu-latest
        steps:
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: '8.2'
            -   uses: actions/checkout@v4
            -   run: composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
            -   run: vendor/bin/phpstan
